Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'RecurringGiftExtension Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "73046151-2e3b-44c6-97cd-c09761045b45", "87a0ccbe-4869-460e-8949-825cde917df5", "Revenue")> _
Partial Public Class [RecurringGiftExtensionEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

#Region "Enums"
	''' <summary>
	''' Enumerated values for use with the FREQUENCYCODE property
	''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public Enum FREQUENCYCODES As Integer
		[Annually] = 0
		[SemiAnnually] = 1
		[Quarterly] = 2
		[Bimonthly] = 6
		[Monthly] = 3
		[SemiMonthly] = 7
		[Biweekly] = 8
		[Weekly] = 9
	End Enum

#End Region


	Private WithEvents _paymentmethodtext As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _frequency As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _amount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _directdebitschedulecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
	Private WithEvents _creditcardschedulecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

	'manually added these so we can have them when saving form:
	Private WithEvents _revenueschedulestartdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
	Private WithEvents _frequencycode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of FREQUENCYCODES)


	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _paymentmethodtext = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _frequency = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _amount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _directdebitschedulecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
		_creditcardschedulecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
		_revenueschedulestartdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
		_frequencycode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of FREQUENCYCODES)

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("73046151-2e3b-44c6-97cd-c09761045b45")
        MyBase.DataFormInstanceId = New Guid("87a0ccbe-4869-460e-8949-825cde917df5")
        MyBase.RecordType = "Revenue"
        MyBase.FORMHEADER.Value = "Edit Payment Schedule"
		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/RecurringGiftExtensionEditDataForm.html"

        '
        '_paymentmethodtext
        '
        _paymentmethodtext.Name = "PAYMENTMETHODTEXT"
        _paymentmethodtext.Caption = "Payment method"
        _paymentmethodtext.DBReadOnly = True
        _paymentmethodtext.MaxLength = 100
        Me.Fields.Add(_paymentmethodtext)
        '
        '_frequency
        '
        _frequency.Name = "FREQUENCY"
        _frequency.Caption = "Frequency"
        _frequency.DBReadOnly = True
        _frequency.MaxLength = 100
        Me.Fields.Add(_frequency)
        '
        '_amount
        '
        _amount.Name = "AMOUNT"
        _amount.Caption = "Amount"
        _amount.DBReadOnly = True
        Me.Fields.Add(_amount)
        '
        '_directdebitschedulecodeid
        '
        _directdebitschedulecodeid.Name = "DIRECTDEBITSCHEDULECODEID"
        _directdebitschedulecodeid.Caption = "Direct debit schedule"
        _directdebitschedulecodeid.CodeTableName = "USR_DIRECTDEBITSCHEDULECODE"
        Me.Fields.Add(_directdebitschedulecodeid)
        '
        '_creditcardschedulecodeid
        '
        _creditcardschedulecodeid.Name = "CREDITCARDSCHEDULECODEID"
        _creditcardschedulecodeid.Caption = "Credit card schedule"
        _creditcardschedulecodeid.CodeTableName = "USR_CREDITCARDSCHEDULECODE"
        Me.Fields.Add(_creditcardschedulecodeid)
		'
		'_revenueschedulestartdate
		'
		_revenueschedulestartdate.Name = "REVENUESCHEDULESTARTDATE"
		_revenueschedulestartdate.Caption = "Starting on"
		_revenueschedulestartdate.Required = False
		Me.Fields.Add(_revenueschedulestartdate)
		'
		'_frequencycode
		'
		_frequencycode.Name = "FREQUENCYCODE"
		_frequencycode.Caption = "Frequency"
		_frequencycode.Required = True
		_frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Annually], .Translation = "Annually"})
		_frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[SemiAnnually], .Translation = "Semi-annually"})
		_frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Quarterly], .Translation = "Quarterly"})
		_frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Bimonthly], .Translation = "Bimonthly"})
		_frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Monthly], .Translation = "Monthly"})
		_frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[SemiMonthly], .Translation = "Semi-monthly"})
		_frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Biweekly], .Translation = "Biweekly"})
		_frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Weekly], .Translation = "Weekly"})
		_frequencycode.Value = FREQUENCYCODES.[Monthly]
		Me.Fields.Add(_frequencycode)


		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Payment method
    ''' </summary>
    <System.ComponentModel.Description("Payment method")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PAYMENTMETHODTEXT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _paymentmethodtext
        End Get
    End Property
    
    ''' <summary>
    ''' Frequency
    ''' </summary>
    <System.ComponentModel.Description("Frequency")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FREQUENCY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _frequency
        End Get
    End Property
    
    ''' <summary>
    ''' Amount
    ''' </summary>
    <System.ComponentModel.Description("Amount")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [AMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _amount
        End Get
    End Property
    
    ''' <summary>
    ''' Direct debit schedule
    ''' </summary>
    <System.ComponentModel.Description("Direct debit schedule")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DIRECTDEBITSCHEDULECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _directdebitschedulecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Credit card schedule
    ''' </summary>
    <System.ComponentModel.Description("Credit card schedule")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CREDITCARDSCHEDULECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _creditcardschedulecodeid
        End Get
    End Property

	''' <summary>
	''' Starting on
	''' </summary>
	<System.ComponentModel.Description("Starting on")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [REVENUESCHEDULESTARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
		Get
			Return _revenueschedulestartdate
		End Get
	End Property

	''' <summary>
	''' Frequency
	''' </summary>
	<System.ComponentModel.Description("Frequency")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [FREQUENCYCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of FREQUENCYCODES)
		Get
			Return _frequencycode
		End Get
	End Property
End Class
