Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Rate Increase Responses Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "cb476753-2237-435f-b308-30df614ffbfb", "0144c06d-d442-4640-bf0c-b0eca083cf74", "SPONSORSHIPS")> _
Partial Public Class [RateIncreaseResponsesEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _ratechangeimplementationdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _ratechangeimplementationdatetext As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _changeyear As Global.Blackbaud.AppFx.UIModeling.Core.YearField
    Private WithEvents _increaserate As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _responsedate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _respondafterratechangeupdated As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _originalsponsorshipgiftamount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _updatedsponsorshipgiftamount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _responseifafterratechangeimplementedcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _noappealresponsedate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _noappealresponsecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _ratechangeimplementationdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _ratechangeimplementationdatetext = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _changeyear = New Global.Blackbaud.AppFx.UIModeling.Core.YearField
        _increaserate = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _responsedate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _respondafterratechangeupdated = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _originalsponsorshipgiftamount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _updatedsponsorshipgiftamount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _responseifafterratechangeimplementedcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _noappealresponsedate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _noappealresponsecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("cb476753-2237-435f-b308-30df614ffbfb")
        MyBase.DataFormInstanceId = New Guid("0144c06d-d442-4640-bf0c-b0eca083cf74")
        MyBase.RecordType = "SPONSORSHIPS"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/RateIncreaseResponsesEditDataForm.html"

        '
        '_ratechangeimplementationdate
        '
        _ratechangeimplementationdate.Name = "RATECHANGEIMPLEMENTATIONDATE"
        _ratechangeimplementationdate.Caption = "Rate Change Implementation Date"
        _ratechangeimplementationdate.Visible = False
        Me.Fields.Add(_ratechangeimplementationdate)
        '
        '_ratechangeimplementationdatetext
        '
        _ratechangeimplementationdatetext.Name = "RATECHANGEIMPLEMENTATIONDATETEXT"
        _ratechangeimplementationdatetext.Caption = "Rate Change Implementation Date Text"
        _ratechangeimplementationdatetext.Visible = False
        _ratechangeimplementationdatetext.MaxLength = 50
        Me.Fields.Add(_ratechangeimplementationdatetext)
        '
        '_changeyear
        '
        _changeyear.Name = "CHANGEYEAR"
        _changeyear.Caption = "Rate Increase Year"
        _changeyear.Required = True
        _changeyear.Visible = False
        Me.Fields.Add(_changeyear)
        '
        '_increaserate
        '
        _increaserate.Name = "INCREASERATE"
        _increaserate.Caption = "Is Rate Increase?"
        _increaserate.Required = True
        Me.Fields.Add(_increaserate)
        '
        '_responsedate
        '
        _responsedate.Name = "RESPONSEDATE"
        _responsedate.Caption = "Response Date"
        _responsedate.Required = True
        Me.Fields.Add(_responsedate)
        '
        '_respondafterratechangeupdated
        '
        _respondafterratechangeupdated.Name = "RESPONDAFTERRATECHANGEUPDATED"
        _respondafterratechangeupdated.Caption = "Response After Rate Change Updated?"
        _respondafterratechangeupdated.Visible = False
        Me.Fields.Add(_respondafterratechangeupdated)
        '
        '_originalsponsorshipgiftamount
        '
        _originalsponsorshipgiftamount.Name = "ORIGINALSPONSORSHIPGIFTAMOUNT"
        _originalsponsorshipgiftamount.Caption = "Original Amount"
        _originalsponsorshipgiftamount.Required = True
        Me.Fields.Add(_originalsponsorshipgiftamount)
        '
        '_updatedsponsorshipgiftamount
        '
        _updatedsponsorshipgiftamount.Name = "UPDATEDSPONSORSHIPGIFTAMOUNT"
        _updatedsponsorshipgiftamount.Caption = "New Amount"
        _updatedsponsorshipgiftamount.Required = True
        Me.Fields.Add(_updatedsponsorshipgiftamount)
        '
        '_responseifafterratechangeimplementedcodeid
        '
        _responseifafterratechangeimplementedcodeid.Name = "RESPONSEIFAFTERRATECHANGEIMPLEMENTEDCODEID"
        _responseifafterratechangeimplementedcodeid.Caption = "Response after implementation?"
        _responseifafterratechangeimplementedcodeid.Visible = False
        _responseifafterratechangeimplementedcodeid.CodeTableName = "USR_RESPONSE_AFTER_RATECHANGE_IMPLEMENTED_CODE"
        Me.Fields.Add(_responseifafterratechangeimplementedcodeid)
        '
        '_noappealresponsedate
        '
        _noappealresponsedate.Name = "NOAPPEALRESPONSEDATE"
        _noappealresponsedate.Caption = "No Appeal Response Date"
        Me.Fields.Add(_noappealresponsedate)
        '
        '_noappealresponsecodeid
        '
        _noappealresponsecodeid.Name = "NOAPPEALRESPONSECODEID"
        _noappealresponsecodeid.Caption = "No Appeal Response Code"
        _noappealresponsecodeid.CodeTableName = "USR_NO_RATEINCREASEAPPEAL_RESPONSECODE"
        Me.Fields.Add(_noappealresponsecodeid)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Rate Change Implementation Date
    ''' </summary>
    <System.ComponentModel.Description("Rate Change Implementation Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RATECHANGEIMPLEMENTATIONDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _ratechangeimplementationdate
        End Get
    End Property
    
    ''' <summary>
    ''' Rate Change Implementation Date Text
    ''' </summary>
    <System.ComponentModel.Description("Rate Change Implementation Date Text")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RATECHANGEIMPLEMENTATIONDATETEXT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _ratechangeimplementationdatetext
        End Get
    End Property
    
    ''' <summary>
    ''' Rate Increase Year
    ''' </summary>
    <System.ComponentModel.Description("Rate Increase Year")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CHANGEYEAR]() As Global.Blackbaud.AppFx.UIModeling.Core.YearField
        Get
            Return _changeyear
        End Get
    End Property
    
    ''' <summary>
    ''' Is Rate Increase?
    ''' </summary>
    <System.ComponentModel.Description("Is Rate Increase?")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [INCREASERATE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _increaserate
        End Get
    End Property
    
    ''' <summary>
    ''' Response Date
    ''' </summary>
    <System.ComponentModel.Description("Response Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RESPONSEDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _responsedate
        End Get
    End Property
    
    ''' <summary>
    ''' Response After Rate Change Updated?
    ''' </summary>
    <System.ComponentModel.Description("Response After Rate Change Updated?")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RESPONDAFTERRATECHANGEUPDATED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _respondafterratechangeupdated
        End Get
    End Property
    
    ''' <summary>
    ''' Original Amount
    ''' </summary>
    <System.ComponentModel.Description("Original Amount")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ORIGINALSPONSORSHIPGIFTAMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _originalsponsorshipgiftamount
        End Get
    End Property
    
    ''' <summary>
    ''' New Amount
    ''' </summary>
    <System.ComponentModel.Description("New Amount")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [UPDATEDSPONSORSHIPGIFTAMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _updatedsponsorshipgiftamount
        End Get
    End Property
    
    ''' <summary>
    ''' Response after implementation?
    ''' </summary>
    <System.ComponentModel.Description("Response after implementation?")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RESPONSEIFAFTERRATECHANGEIMPLEMENTEDCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _responseifafterratechangeimplementedcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' No Appeal Response Date
    ''' </summary>
    <System.ComponentModel.Description("No Appeal Response Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [NOAPPEALRESPONSEDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _noappealresponsedate
        End Get
    End Property
    
    ''' <summary>
    ''' No Appeal Response Code
    ''' </summary>
    <System.ComponentModel.Description("No Appeal Response Code")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [NOAPPEALRESPONSECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _noappealresponsecodeid
        End Get
    End Property
    
End Class
