Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'SponsorshipOpportunityChild_MoMCustom Search' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.SearchListUIModelMetadata("f9183b88-9f54-40de-848e-c8fbacf92e79", "Sponsorship Opportunity", "SPSponsorshipOppChileSrchScreen.html")> _
Partial Public Class [SponsorshipOpportunityChildMoMCustomSearchUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.SearchListUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the ELIGIBILITYCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Enum ELIGIBILITYCODES As Integer
        [Pending] = 0
        [Eligible] = 1
        [Ineligible] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the AVAILABILITYCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Enum AVAILABILITYCODES As Integer
        [Available] = 0
        [Reserved] = 1
        [Unavailable] = 2
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _quicksearch As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _keyname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _firstname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _sponsorshipopportunitygroupid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _sponsorshipprogramid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _sponsorshiplocationid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _lookupid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _eligibilitycode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ELIGIBILITYCODES))
    Private WithEvents _availabilitycode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of AVAILABILITYCODES))
    Private WithEvents _restrictforsolesponsorship As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _excludeopportunityid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _reservationkeyid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _sponsorshipopportunityid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _correspondingsponsorid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _financialsponsorid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Sub New()
        MyBase.New()

        _quicksearch = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _keyname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _firstname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _sponsorshipopportunitygroupid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _sponsorshipprogramid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _sponsorshiplocationid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _lookupid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _eligibilitycode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ELIGIBILITYCODES))
        _availabilitycode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of AVAILABILITYCODES))
        _restrictforsolesponsorship = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _excludeopportunityid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _reservationkeyid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _sponsorshipopportunityid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _correspondingsponsorid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _financialsponsorid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField

        MyBase.SearchListId = New Guid("ab076868-114a-4696-afe9-8d590677708c")
        MyBase.SearchRecordType = "Sponsorship opportunity"
        MyBase.FORMHEADER.Value = "Sponsorship Opportunity Child Search Custom"
        MyBase.HelpKey = "SPSponsorshipOppChileSrchScreen.html"
        MyBase.TranslationFunctionId = New Guid("266f9175-c97b-46a5-b125-2d90820eb8d4")
        MyBase.QuickFindCriteriaFieldId = "QUICKSEARCH"
        MyBase.ImageKey = "catalog:Blackbaud.AppFx.Sponsorship.Catalog.dll,Blackbaud.AppFx.Sponsorship.Catalog.child_search_32.png"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/SponsorshipOpportunityChildMoMCustomSearch.html"

        '
        '_quicksearch
        '
        _quicksearch.Name = "QUICKSEARCH"
        _quicksearch.Caption = "QUICKSEARCH"
        _quicksearch.Visible = False
        _quicksearch.MaxLength = 100
        Me.Fields.Add(_quicksearch)
        '
        '_keyname
        '
        _keyname.Name = "KEYNAME"
        _keyname.Caption = "Last name"
        _keyname.MaxLength = 100
        Me.Fields.Add(_keyname)
        '
        '_firstname
        '
        _firstname.Name = "FIRSTNAME"
        _firstname.Caption = "First name"
        _firstname.MaxLength = 100
        Me.Fields.Add(_firstname)
        '
        '_sponsorshipopportunitygroupid
        '
        _sponsorshipopportunitygroupid.Name = "SPONSORSHIPOPPORTUNITYGROUPID"
        _sponsorshipopportunitygroupid.Caption = "Child group"
        _sponsorshipopportunitygroupid.SimpleDataListID = New Guid("755c0b35-29bb-40df-85a2-7054c986c6f6")
        _sponsorshipopportunitygroupid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPE", "1"))
        _sponsorshipopportunitygroupid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("INCLUDEINACTIVE", "1"))
        Me.Fields.Add(_sponsorshipopportunitygroupid)
        '
        '_sponsorshipprogramid
        '
        _sponsorshipprogramid.Name = "SPONSORSHIPPROGRAMID"
        _sponsorshipprogramid.Caption = "Sponsorship program"
        _sponsorshipprogramid.SimpleDataListID = New Guid("fca96cc4-1aad-4072-8bca-ba010e9e4e31")
        _sponsorshipprogramid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPE", "1"))
        _sponsorshipprogramid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("INCLUDEINACTIVE", "1"))
        Me.Fields.Add(_sponsorshipprogramid)
        '
        '_sponsorshiplocationid
        '
        _sponsorshiplocationid.Name = "SPONSORSHIPLOCATIONID"
        _sponsorshiplocationid.Caption = "Location"
        _sponsorshiplocationid.SearchListID = New Guid("7d7ac450-86f7-42f7-9299-e2458592ad14")
        _sponsorshiplocationid.EnableQuickFind = True
        _sponsorshiplocationid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "WITHINLOCATION", .Hidden = True})
        _sponsorshiplocationid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "WITHINLOCATIONDISPLAY", .Hidden = True})
        Me.Fields.Add(_sponsorshiplocationid)
        '
        '_lookupid
        '
        _lookupid.Name = "LOOKUPID"
        _lookupid.Caption = "Lookup ID"
        _lookupid.MaxLength = 100
        Me.Fields.Add(_lookupid)
        '
        '_eligibilitycode
        '
        _eligibilitycode.Name = "ELIGIBILITYCODE"
        _eligibilitycode.Caption = "Eligibility"
        _eligibilitycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ELIGIBILITYCODES)) With {.Value = ELIGIBILITYCODES.[Pending], .Translation = "Pending"})
        _eligibilitycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ELIGIBILITYCODES)) With {.Value = ELIGIBILITYCODES.[Eligible], .Translation = "Eligible"})
        _eligibilitycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ELIGIBILITYCODES)) With {.Value = ELIGIBILITYCODES.[Ineligible], .Translation = "Ineligible"})
        Me.Fields.Add(_eligibilitycode)
        '
        '_availabilitycode
        '
        _availabilitycode.Name = "AVAILABILITYCODE"
        _availabilitycode.Caption = "Availability"
        _availabilitycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of AVAILABILITYCODES)) With {.Value = AVAILABILITYCODES.[Available], .Translation = "Available"})
        _availabilitycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of AVAILABILITYCODES)) With {.Value = AVAILABILITYCODES.[Reserved], .Translation = "Reserved"})
        _availabilitycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of AVAILABILITYCODES)) With {.Value = AVAILABILITYCODES.[Unavailable], .Translation = "Unavailable"})
        Me.Fields.Add(_availabilitycode)
        '
        '_restrictforsolesponsorship
        '
        _restrictforsolesponsorship.Name = "RESTRICTFORSOLESPONSORSHIP"
        _restrictforsolesponsorship.Caption = "Only include unsponsored"
        _restrictforsolesponsorship.Visible = False
        Me.Fields.Add(_restrictforsolesponsorship)
        '
        '_excludeopportunityid
        '
        _excludeopportunityid.Name = "EXCLUDEOPPORTUNITYID"
        _excludeopportunityid.Caption = "EXCLUDEOPPORTUNITYID"
        _excludeopportunityid.Visible = False
        Me.Fields.Add(_excludeopportunityid)
        '
        '_reservationkeyid
        '
        _reservationkeyid.Name = "RESERVATIONKEYID"
        _reservationkeyid.Caption = "Reservation key"
        _reservationkeyid.SearchListID = New Guid("617890dc-3770-4505-b963-b6072cadced7")
        _reservationkeyid.EnableQuickFind = True
        Me.Fields.Add(_reservationkeyid)
        '
        '_sponsorshipopportunityid
        '
        _sponsorshipopportunityid.Name = "SPONSORSHIPOPPORTUNITYID"
        _sponsorshipopportunityid.Caption = "SPONSORSHIPOPPORTUNITYID"
        _sponsorshipopportunityid.Visible = False
        Me.Fields.Add(_sponsorshipopportunityid)
        '
        '_correspondingsponsorid
        '
        _correspondingsponsorid.Name = "CORRESPONDINGSPONSORID"
        _correspondingsponsorid.Caption = "CORRESPONDINGSPONSORID"
        _correspondingsponsorid.Visible = False
        Me.Fields.Add(_correspondingsponsorid)
        '
        '_financialsponsorid
        '
        _financialsponsorid.Name = "FINANCIALSPONSORID"
        _financialsponsorid.Caption = "FINANCIALSPONSORID"
        _financialsponsorid.Visible = False
        Me.Fields.Add(_financialsponsorid)

        OnCreated()

    End Sub

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [QUICKSEARCH]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _quicksearch
        End Get
    End Property

    ''' <summary>
    ''' Last name
    ''' </summary>
    <System.ComponentModel.Description("Last name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [KEYNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _keyname
        End Get
    End Property

    ''' <summary>
    ''' First name
    ''' </summary>
    <System.ComponentModel.Description("First name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [FIRSTNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _firstname
        End Get
    End Property

    ''' <summary>
    ''' Child group
    ''' </summary>
    <System.ComponentModel.Description("Child group")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYGROUPID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _sponsorshipopportunitygroupid
        End Get
    End Property

    ''' <summary>
    ''' Sponsorship program
    ''' </summary>
    <System.ComponentModel.Description("Sponsorship program")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [SPONSORSHIPPROGRAMID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _sponsorshipprogramid
        End Get
    End Property

    ''' <summary>
    ''' Location
    ''' </summary>
    <System.ComponentModel.Description("Location")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [SPONSORSHIPLOCATIONID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _sponsorshiplocationid
        End Get
    End Property

    ''' <summary>
    ''' Lookup ID
    ''' </summary>
    <System.ComponentModel.Description("Lookup ID")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [LOOKUPID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _lookupid
        End Get
    End Property

    ''' <summary>
    ''' Eligibility
    ''' </summary>
    <System.ComponentModel.Description("Eligibility")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ELIGIBILITYCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ELIGIBILITYCODES))
        Get
            Return _eligibilitycode
        End Get
    End Property

    ''' <summary>
    ''' Availability
    ''' </summary>
    <System.ComponentModel.Description("Availability")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [AVAILABILITYCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of AVAILABILITYCODES))
        Get
            Return _availabilitycode
        End Get
    End Property

    ''' <summary>
    ''' Only include unsponsored
    ''' </summary>
    <System.ComponentModel.Description("Only include unsponsored")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [RESTRICTFORSOLESPONSORSHIP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _restrictforsolesponsorship
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [EXCLUDEOPPORTUNITYID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _excludeopportunityid
        End Get
    End Property

    ''' <summary>
    ''' Reservation key
    ''' </summary>
    <System.ComponentModel.Description("Reservation key")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [RESERVATIONKEYID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _reservationkeyid
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _sponsorshipopportunityid
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [CORRESPONDINGSPONSORID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _correspondingsponsorid
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [FINANCIALSPONSORID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _financialsponsorid
        End Get
    End Property

End Class
