Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'SponsorshipAddFormWrappedCHILDREN' data form
''' </summary>
Partial Public Class [SponsorshipAddFormWrappedCHILDRENUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    'TESTING ONLY Memphis added these to test if the fields are present and populated, does the search work?
    'Private WithEvents _sponsorshipconstituentid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    'Private WithEvents _sponsorshipprogramid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    'Private WithEvents _revenueconstituentid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    ' Done adding

    Private WithEvents _id As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _name As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _namesearchaction As Global.Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction
    Private WithEvents _lookupid As Global.Blackbaud.AppFx.UIModeling.Core.StringField


    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        'Added by Memphis to TEST:
        '_sponsorshipconstituentid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        '_sponsorshipprogramid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        '_revenueconstituentid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        'Done adding

        _id = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _name = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _namesearchaction = New Global.Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction
        _lookupid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        '
        '_id
        '
        _id.Name = "ID"
        _id.Caption = "ID"
        _id.Visible = False
        Me.Fields.Add(_id)
        '
        '_name
        '
        _name.Name = "NAME"
        _name.Caption = "Child Name"
        _name.Required = True
        _name.SimpleDataListId = New Guid("3eb2bc55-07d8-4b1d-9a48-33883b3fa404")
        Me.Fields.Add(_name)
        '
        ' _lookupid
        '
        _lookupid.Name = "LOOKUPID"
        _lookupid.Caption = "Lookup ID"
        _lookupid.Required = False
        Me.Fields.Add(_lookupid)


        ' Memphis commented out: the search doesn't work correctly, apparently it's a bug:
        '
        '_namesearchaction
        '
        '_namesearchaction.Name = "NAMESEARCHACTION"
        '_namesearchaction.Caption = "Search"
        '_namesearchaction.SearchListId = New Guid("ab076868-114a-4696-afe9-8d590677708c")
        '_namesearchaction.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "SPONSORSHIPPROGRAMID", .ReadOnly = False, .DefaultValueText = "Fields!SPONSORSHIPPROGRAMID"})
        '_namesearchaction.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "ELIGIBILITYCODE", .ReadOnly = False, .DefaultValueText = "1"})
        '_namesearchaction.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "AVAILABILITYCODE", .ReadOnly = False, .DefaultValueText = "0"})
        '_namesearchaction.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RESTRICTFORSOLESPONSORSHIP", .Caption = "Only include unsponsored", .DefaultValueText = "Fields!ISSOLESPONSORSHIP"})
        '_namesearchaction.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "SPONSORSHIPOPPORTUNITYGROUPID", .ReadOnly = False})
        '_namesearchaction.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RESERVATIONKEYID", .ReadOnly = False})
        '_namesearchaction.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "CORRESPONDINGSPONSORID", .Hidden = True, .DefaultValueText = "Fields!SPONSORSHIPCONSTITUENTID"})
        '_namesearchaction.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "FINANCIALSPONSORID", .Hidden = True, .DefaultValueText = "Fields!REVENUECONSTITUENTID"})

        'Me.Actions.Add(_namesearchaction)

        '_name.LinkedActions.Add(_namesearchaction)

        'AddHandler _namesearchaction.Search, AddressOf SearchingForChild
        ' End of commented-out section


        'Memphis added to TEST:
        ''
        ''_sponsorshipconstituentid
        ''
        '_sponsorshipconstituentid.Name = "SPONSORSHIPCONSTITUENTID"
        '_sponsorshipconstituentid.Caption = "Corresponding sponsor"
        '_sponsorshipconstituentid.Required = True
        '_sponsorshipconstituentid.SearchListId = New Guid("23c5c603-d7d8-4106-aecc-65392b563887")
        '_sponsorshipconstituentid.EnableQuickFind = True
        '_sponsorshipconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("6949e415-6cd0-4af5-be9f-acebd318f478"), "Individual"))
        '_sponsorshipconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("d846a816-46c7-470e-9ad0-973b2730e836"), "Household"))
        '_sponsorshipconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("f0f6426a-fccd-48bb-846b-eb3d1a4a0ed4"), "Group"))
        '_sponsorshipconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("0706d187-af1a-4bd6-8365-8fb7419e5600"), "Organization"))
        '_sponsorshipconstituentid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "INCLUDENONCONSTITUENTRECORDS", .Hidden = True, .DefaultValueText = "true"})
        '_sponsorshipconstituentid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "FORMHEADER", .DefaultValueText = "Record Search"})
        'Me.Fields.Add(_sponsorshipconstituentid)
        ''
        ''_sponsorshipprogramid
        ''
        '_sponsorshipprogramid.Name = "SPONSORSHIPPROGRAMID"
        '_sponsorshipprogramid.Caption = "Program"
        '_sponsorshipprogramid.Required = True
        '_sponsorshipprogramid.SimpleDataListId = New Guid("fca96cc4-1aad-4072-8bca-ba010e9e4e31")
        '_sponsorshipprogramid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPE", "0"))
        'Me.Fields.Add(_sponsorshipprogramid)
        ''
        ''_revenueconstituentid
        ''
        '_revenueconstituentid.Name = "REVENUECONSTITUENTID"
        '_revenueconstituentid.Caption = "Financial sponsor"
        '_revenueconstituentid.Required = True
        '_revenueconstituentid.SearchListId = New Guid("23c5c603-d7d8-4106-aecc-65392b563887")
        '_revenueconstituentid.EnableQuickFind = True
        '_revenueconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("6949e415-6cd0-4af5-be9f-acebd318f478"), "Individual"))
        '_revenueconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("d846a816-46c7-470e-9ad0-973b2730e836"), "Household"))
        '_revenueconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("f0f6426a-fccd-48bb-846b-eb3d1a4a0ed4"), "Group"))
        '_revenueconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("0706d187-af1a-4bd6-8365-8fb7419e5600"), "Organization"))
        '_revenueconstituentid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "INCLUDENONCONSTITUENTRECORDS", .Hidden = True, .DefaultValueText = "true"})
        '_revenueconstituentid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "FORMHEADER", .DefaultValueText = "Record Search"})
        'Me.Fields.Add(_revenueconstituentid)

        'Done adding


        OnCreated()

    End Sub

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Property [ID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _id
        End Get
        Set(ByVal value As Global.Blackbaud.AppFx.UIModeling.Core.GuidField)

        End Set
    End Property

    ''' <summary>
    ''' Child Name
    ''' </summary>
    <System.ComponentModel.Description("Child Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Property [NAME]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _name
        End Get
        Set(ByVal value As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid))

        End Set
    End Property

    ''' <summary>
    ''' LookupID
    ''' </summary>
    <System.ComponentModel.Description("Lookup ID")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Property [LOOKUPID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _lookupid
        End Get
        Set(ByVal value As Global.Blackbaud.AppFx.UIModeling.Core.StringField)

        End Set
    End Property


    ''' <summary>
    ''' Search
    ''' </summary>
    <System.ComponentModel.Description("Search")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [NAMESEARCHACTION]() As Global.Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction
        Get
            Return _namesearchaction
        End Get
    End Property

    'Added by Memphis for TEST:
    '''' <summary>
    '''' Corresponding sponsor
    '''' </summary>
    '<System.ComponentModel.Description("Corresponding sponsor")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    'Public ReadOnly Property [SPONSORSHIPCONSTITUENTID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    '    Get
    '        Return _sponsorshipconstituentid
    '    End Get
    'End Property

    '''' <summary>
    '''' Program
    '''' </summary>
    '<System.ComponentModel.Description("Program")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    'Public ReadOnly Property [SPONSORSHIPPROGRAMID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    '    Get
    '        Return _sponsorshipprogramid
    '    End Get
    'End Property

    '''' <summary>
    '''' Financial sponsor
    '''' </summary>
    '<System.ComponentModel.Description("Financial sponsor")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    'Public ReadOnly Property [REVENUECONSTITUENTID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    '    Get
    '        Return _revenueconstituentid
    '    End Get
    'End Property
    'Done adding


End Class
