Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Sponsorship UI Model Version' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "952311b1-3f23-413f-bea4-d3225e623589", "6277e024-cccd-4b4e-ba53-4fed4b2133e9", "Sponsorship")> _
Partial Public Class [SponsorshipUIModelVersionUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _version As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _version = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("952311b1-3f23-413f-bea4-d3225e623589")
        MyBase.DataFormInstanceId = New Guid("6277e024-cccd-4b4e-ba53-4fed4b2133e9")
        MyBase.RecordType = "Sponsorship"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/Sponsorship.UIModelVersion.ViewForm.html"

        '
        '_version
        '
        _version.Name = "VERSION"
        _version.Caption = "Sponsorship UI Model:"
        _version.DBReadOnly = True
        _version.MaxLength = 50
        Me.Fields.Add(_version)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Sponsorship UI Model
    ''' </summary>
    <System.ComponentModel.Description("Sponsorship UI Model")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [VERSION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _version
        End Get
    End Property
    
End Class
