Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Sponsorship Add Form (Wrapped)' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "32ce36c3-3881-4b80-b7a9-94eef6a58cb7", "bd01386b-95f1-47d4-aab5-49822ed9126f", "Sponsorship", "SPAddASponsorshipScr.html")> _
Partial Public Class [SponsorshipAddFormWrappedUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the GENDERCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum GENDERCODES As Integer
        [Male] = 1
        [Female] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the ISHIVPOSITIVECODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum ISHIVPOSITIVECODES As Integer
        [Yes] = 1
        [No] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the HASCONDITIONCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum HASCONDITIONCODES As Integer
        [Yes] = 1
        [No] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the ISORPHANEDCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum ISORPHANEDCODES As Integer
        [Yes] = 1
        [No] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the PAYMENTMETHODCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum PAYMENTMETHODCODES As Integer
        [CreditCard] = 2
        [DirectDebit] = 3
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the FREQUENCYCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum FREQUENCYCODES As Integer
        [Annually] = 0
        [SemiAnnually] = 1
        [Quarterly] = 2
        [Bimonthly] = 6
        [Monthly] = 3
        [SemiMonthly] = 7
        [Biweekly] = 8
        [Weekly] = 9
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the SELECTOPPORTUNITYID property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum SELECTOPPORTUNITYIDS As Integer
        [ChooseASpecificOpportunity] = 0
        [ChooseAReservedOpportunity] = 1
        [FindAMatchingOpportunityOfGreatestNeed] = 2
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _formtitle As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _revenueconstituentid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _giftrecipient As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _sponsorshipconstituentid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _sponsorshipreasonid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _sponsorshipprogramid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _children As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of SponsorshipAddFormWrappedCHILDRENUIModel)
    Private WithEvents _plannedenddate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _sponsorshiplocationid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _sproppagerangeid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _gendercode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of GENDERCODES))
    Private WithEvents _ishivpositivecode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISHIVPOSITIVECODES))
    Private WithEvents _hasconditioncode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of HASCONDITIONCODES))
    Private WithEvents _isorphanedcode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISORPHANEDCODES))
    Private WithEvents _sproppprojectcategorycodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _sponsorshipopportunityidchild As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _sponsorshipopportunityidproject As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _issolesponsorship As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _startdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _amount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _autopay As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _paymentmethodcode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of PAYMENTMETHODCODES)
    Private WithEvents _constituentaccountid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _constituentaccountidaddaccountaction As Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction
    Private WithEvents _referencenumber As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _referencedate As Global.Blackbaud.AppFx.UIModeling.Core.FuzzyDateField
    Private WithEvents _frequencycode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of FREQUENCYCODES)
    Private WithEvents _revenueschedulestartdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _revenuescheduleenddate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _creditcardnumber As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _cardholdername As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _expireson As Global.Blackbaud.AppFx.UIModeling.Core.FuzzyDateField
    Private WithEvents _creditcardtoken As Global.Blackbaud.AppFx.UIModeling.Core.CreditCardTokenField
    Private WithEvents _credittypecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _reservedopportunityidchild As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _reservationkey As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _matchedopportunityid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _sendreminder As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _findernumber As Global.Blackbaud.AppFx.UIModeling.Core.LongField
    Private WithEvents _sourcecode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _appealid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _mailingid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _channelcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _reference As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _categorycodeid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _expirationreasonid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _transactioncurrencyid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _baseexchangerateid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _exchangerate As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
    Private WithEvents _basecurrencyid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _baseamount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _basecurrencydecimaldigits As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _basecurrencyroundingtypecode As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _batchnumber As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _revenuedevelopmentfunctioncodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _donotacknowledge As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _selectopportunityid As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of SELECTOPPORTUNITYIDS))
    Private WithEvents _isfixedtermsponsorship As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _rgschedule As Global.Blackbaud.AppFx.UIModeling.Core.XMLField
    Private WithEvents _mopportunityname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _mopportunitylocation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _mopportunitylookupid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _mopportunitygender As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _mopportunitybirthdate As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _mopportunityimage As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _findernumberstring As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _invalidfindernumberimage As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _installments As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of SponsorshipAddFormWrappedINSTALLMENTSUIModel)
    Private WithEvents _generalinformation As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _sponsorshipopportunity As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _paymentschedule As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _paymentinformation As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _matchedopportunity As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _tabsponsorship As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _tabpayment As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _tabexpiration As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _findopportunity As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _removeselectedchild As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _addselectedchild As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _sourcecodelookup As Global.Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction
	Private WithEvents _currencyaction As Global.Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction
	Private WithEvents _clearsearchaction As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction


    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _formtitle = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _revenueconstituentid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _giftrecipient = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _sponsorshipconstituentid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _sponsorshipreasonid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _sponsorshipprogramid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _children = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of SponsorshipAddFormWrappedCHILDRENUIModel)
        _plannedenddate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _sponsorshiplocationid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _sproppagerangeid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _gendercode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of GENDERCODES))
        _ishivpositivecode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISHIVPOSITIVECODES))
        _hasconditioncode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of HASCONDITIONCODES))
        _isorphanedcode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISORPHANEDCODES))
        _sproppprojectcategorycodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _sponsorshipopportunityidchild = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _sponsorshipopportunityidproject = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _issolesponsorship = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _startdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _amount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _autopay = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _paymentmethodcode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of PAYMENTMETHODCODES)
        _constituentaccountid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _constituentaccountidaddaccountaction = New Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction
        _referencenumber = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _referencedate = New Global.Blackbaud.AppFx.UIModeling.Core.FuzzyDateField
        _frequencycode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of FREQUENCYCODES)
        _revenueschedulestartdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _revenuescheduleenddate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _creditcardnumber = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _cardholdername = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _expireson = New Global.Blackbaud.AppFx.UIModeling.Core.FuzzyDateField
        _creditcardtoken = New Global.Blackbaud.AppFx.UIModeling.Core.CreditCardTokenField
        _credittypecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _reservedopportunityidchild = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _reservationkey = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _matchedopportunityid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _sendreminder = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _findernumber = New Global.Blackbaud.AppFx.UIModeling.Core.LongField
        _sourcecode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _appealid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _mailingid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _channelcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _reference = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _categorycodeid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _expirationreasonid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _transactioncurrencyid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _baseexchangerateid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _exchangerate = New Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        _basecurrencyid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _baseamount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _basecurrencydecimaldigits = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _basecurrencyroundingtypecode = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _batchnumber = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _revenuedevelopmentfunctioncodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _donotacknowledge = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _selectopportunityid = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of SELECTOPPORTUNITYIDS))
        _isfixedtermsponsorship = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _rgschedule = New Global.Blackbaud.AppFx.UIModeling.Core.XMLField
        _mopportunityname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _mopportunitylocation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _mopportunitylookupid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _mopportunitygender = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _mopportunitybirthdate = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _mopportunityimage = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _findernumberstring = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _invalidfindernumberimage = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _installments = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of SponsorshipAddFormWrappedINSTALLMENTSUIModel)
        _generalinformation = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _sponsorshipopportunity = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _paymentschedule = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _paymentinformation = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _matchedopportunity = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _tabsponsorship = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _tabpayment = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _tabexpiration = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _findopportunity = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _removeselectedchild = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _addselectedchild = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _sourcecodelookup = New Global.Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction
		_currencyaction = New Global.Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction
		_clearsearchaction = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New Guid("32ce36c3-3881-4b80-b7a9-94eef6a58cb7")
        MyBase.DataFormInstanceId = New Guid("bd01386b-95f1-47d4-aab5-49822ed9126f")
        MyBase.RecordType = "Sponsorship"
        MyBase.HelpKey = "SPAddASponsorshipScr.html"
        MyBase.FixedDialog = True
        MyBase.FORMHEADER.Value = "Add a sponsorship"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/SponsorshipAddFormWrapped.html"

        '
        '_formtitle
        '
        _formtitle.Name = "FORMTITLE"
        _formtitle.Caption = "FORMTITLE"
        _formtitle.DBReadOnly = True
        _formtitle.MaxLength = 100
        Me.Fields.Add(_formtitle)
        '
        '_revenueconstituentid
        '
        _revenueconstituentid.Name = "REVENUECONSTITUENTID"
        _revenueconstituentid.Caption = "Financial sponsor"
        _revenueconstituentid.Required = True
        _revenueconstituentid.SearchListID = New Guid("23c5c603-d7d8-4106-aecc-65392b563887")
        _revenueconstituentid.EnableQuickFind = True
        _revenueconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("6949e415-6cd0-4af5-be9f-acebd318f478"), "Individual"))
        _revenueconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("d846a816-46c7-470e-9ad0-973b2730e836"), "Household"))
        _revenueconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("f0f6426a-fccd-48bb-846b-eb3d1a4a0ed4"), "Group"))
        _revenueconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("0706d187-af1a-4bd6-8365-8fb7419e5600"), "Organization"))
        _revenueconstituentid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "INCLUDENONCONSTITUENTRECORDS", .Hidden = True, .DefaultValueText = "true"})
        _revenueconstituentid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "FORMHEADER", .DefaultValueText = "Record Search"})
        Me.Fields.Add(_revenueconstituentid)
        '
        '_giftrecipient
        '
        _giftrecipient.Name = "GIFTRECIPIENT"
        _giftrecipient.Caption = "Gift"
        Me.Fields.Add(_giftrecipient)
        '
        '_sponsorshipconstituentid
        '
        _sponsorshipconstituentid.Name = "SPONSORSHIPCONSTITUENTID"
        _sponsorshipconstituentid.Caption = "Corresponding sponsor"
        _sponsorshipconstituentid.Required = True
        _sponsorshipconstituentid.SearchListID = New Guid("23c5c603-d7d8-4106-aecc-65392b563887")
        _sponsorshipconstituentid.EnableQuickFind = True
        _sponsorshipconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("6949e415-6cd0-4af5-be9f-acebd318f478"), "Individual"))
        _sponsorshipconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("d846a816-46c7-470e-9ad0-973b2730e836"), "Household"))
        _sponsorshipconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("f0f6426a-fccd-48bb-846b-eb3d1a4a0ed4"), "Group"))
        _sponsorshipconstituentid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("0706d187-af1a-4bd6-8365-8fb7419e5600"), "Organization"))
        _sponsorshipconstituentid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "INCLUDENONCONSTITUENTRECORDS", .Hidden = True, .DefaultValueText = "true"})
        _sponsorshipconstituentid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "FORMHEADER", .DefaultValueText = "Record Search"})
        Me.Fields.Add(_sponsorshipconstituentid)
        '
        '_sponsorshipreasonid
        '
        _sponsorshipreasonid.Name = "SPONSORSHIPREASONID"
        _sponsorshipreasonid.Caption = "Reason"
        _sponsorshipreasonid.Visible = False
        _sponsorshipreasonid.DBReadOnly = True
        _sponsorshipreasonid.SimpleDataListID = New Guid("c8d3128e-a2eb-4413-b0b4-1585ad5bf001")
        Me.Fields.Add(_sponsorshipreasonid)
        '
        '_sponsorshipprogramid
        '
        _sponsorshipprogramid.Name = "SPONSORSHIPPROGRAMID"
        _sponsorshipprogramid.Caption = "Program"
        _sponsorshipprogramid.Required = True
        _sponsorshipprogramid.SimpleDataListID = New Guid("fca96cc4-1aad-4072-8bca-ba010e9e4e31")
        _sponsorshipprogramid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPE", "0"))
        Me.Fields.Add(_sponsorshipprogramid)
        '
        '_children
        '
        _children.Name = "CHILDREN"
        _children.Caption = "Children"
        Me.Fields.Add(_children)
        '
        '_plannedenddate
        '
        _plannedenddate.Name = "PLANNEDENDDATE"
        _plannedenddate.Caption = "Expiration date"
        Me.Fields.Add(_plannedenddate)
        '
        '_sponsorshiplocationid
        '
        _sponsorshiplocationid.Name = "SPONSORSHIPLOCATIONID"
        _sponsorshiplocationid.Caption = "Location"
        _sponsorshiplocationid.SearchListID = New Guid("7d7ac450-86f7-42f7-9299-e2458592ad14")
        _sponsorshiplocationid.EnableQuickFind = True
        _sponsorshiplocationid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "WITHINLOCATION", .Hidden = True})
        _sponsorshiplocationid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "WITHINLOCATIONDISPLAY", .Hidden = True})
        Me.Fields.Add(_sponsorshiplocationid)
        '
        '_sproppagerangeid
        '
        _sproppagerangeid.Name = "SPROPPAGERANGEID"
        _sproppagerangeid.Caption = "Age range"
        _sproppagerangeid.SimpleDataListID = New Guid("b2b6fb02-19df-49d4-8092-de9611e98b2a")
        Me.Fields.Add(_sproppagerangeid)
        '
        '_gendercode
        '
        _gendercode.Name = "GENDERCODE"
        _gendercode.Caption = "Gender"
        _gendercode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of GENDERCODES)) With {.Value = GENDERCODES.[Male], .Translation = "Male"})
        _gendercode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of GENDERCODES)) With {.Value = GENDERCODES.[Female], .Translation = "Female"})
        Me.Fields.Add(_gendercode)
        '
        '_ishivpositivecode
        '
        _ishivpositivecode.Name = "ISHIVPOSITIVECODE"
        _ishivpositivecode.Caption = "HIV positive"
        _ishivpositivecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISHIVPOSITIVECODES)) With {.Value = ISHIVPOSITIVECODES.[Yes], .Translation = "Yes"})
        _ishivpositivecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISHIVPOSITIVECODES)) With {.Value = ISHIVPOSITIVECODES.[No], .Translation = "No"})
        Me.Fields.Add(_ishivpositivecode)
        '
        '_hasconditioncode
        '
        _hasconditioncode.Name = "HASCONDITIONCODE"
        _hasconditioncode.Caption = "Disability/Illness"
        _hasconditioncode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of HASCONDITIONCODES)) With {.Value = HASCONDITIONCODES.[Yes], .Translation = "Yes"})
        _hasconditioncode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of HASCONDITIONCODES)) With {.Value = HASCONDITIONCODES.[No], .Translation = "No"})
        Me.Fields.Add(_hasconditioncode)
        '
        '_isorphanedcode
        '
        _isorphanedcode.Name = "ISORPHANEDCODE"
        _isorphanedcode.Caption = "Orphaned"
        _isorphanedcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISORPHANEDCODES)) With {.Value = ISORPHANEDCODES.[Yes], .Translation = "Yes"})
        _isorphanedcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISORPHANEDCODES)) With {.Value = ISORPHANEDCODES.[No], .Translation = "No"})
        Me.Fields.Add(_isorphanedcode)
        '
        '_sproppprojectcategorycodeid
        '
        _sproppprojectcategorycodeid.Name = "SPROPPPROJECTCATEGORYCODEID"
        _sproppprojectcategorycodeid.Caption = "Category"
        _sproppprojectcategorycodeid.CodeTableName = "SPROPPPROJECTCATEGORYCODE"
        Me.Fields.Add(_sproppprojectcategorycodeid)
        '
        '_sponsorshipopportunityidchild
        '
        _sponsorshipopportunityidchild.Name = "SPONSORSHIPOPPORTUNITYIDCHILD"
        _sponsorshipopportunityidchild.Caption = "Child"
        'we're now calling our own custom child search form with ID=f9183b88-9f54-40de-848e-c8fbacf92e79
        _sponsorshipopportunityidchild.SearchListId = New Guid("f9183b88-9f54-40de-848e-c8fbacf92e79") ' New Guid("ab076868-114a-4696-afe9-8d590677708c") -- this is the OOB Search form
        _sponsorshipopportunityidchild.EnableQuickFind = False ' True - changed by Memphis to test
        _sponsorshipopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "SPONSORSHIPPROGRAMID", .ReadOnly = False, .DefaultValueText = "Fields!SPONSORSHIPPROGRAMID"})
        _sponsorshipopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "ELIGIBILITYCODE", .ReadOnly = False, .DefaultValueText = "1"})
        _sponsorshipopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "AVAILABILITYCODE", .ReadOnly = False, .DefaultValueText = "1"})
        _sponsorshipopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RESTRICTFORSOLESPONSORSHIP", .Caption = "Only include unsponsored", .DefaultValueText = "True"}) '.DefaultValueText = "Fields!ISSOLESPONSORSHIP"
        _sponsorshipopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "SPONSORSHIPOPPORTUNITYGROUPID", .ReadOnly = False})
        _sponsorshipopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RESERVATIONKEYID", .ReadOnly = False})
        _sponsorshipopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "CORRESPONDINGSPONSORID", .Hidden = True, .DefaultValueText = "Fields!SPONSORSHIPCONSTITUENTID"})
        _sponsorshipopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "FINANCIALSPONSORID", .Hidden = True, .DefaultValueText = "Fields!REVENUECONSTITUENTID"})
        Me.Fields.Add(_sponsorshipopportunityidchild)

        'added by memphis to test:
        AddHandler _sponsorshipopportunityidchild.Search, AddressOf SearchingForChild



        '
        '_sponsorshipopportunityidproject
        '
        _sponsorshipopportunityidproject.Name = "SPONSORSHIPOPPORTUNITYIDPROJECT"
        _sponsorshipopportunityidproject.Caption = "Project"
        _sponsorshipopportunityidproject.SearchListID = New Guid("b095dc74-4c09-40c9-9c9d-e8ff55b584ce")
        _sponsorshipopportunityidproject.EnableQuickFind = True
        _sponsorshipopportunityidproject.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "SPONSORSHIPPROGRAMID", .ReadOnly = True, .DefaultValueText = "Fields!SPONSORSHIPPROGRAMID"})
        _sponsorshipopportunityidproject.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "ELIGIBILITYCODE", .ReadOnly = True, .DefaultValueText = "1"})
        _sponsorshipopportunityidproject.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "AVAILABILITYCODE", .ReadOnly = True, .DefaultValueText = "0"})
        _sponsorshipopportunityidproject.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RESTRICTFORSOLESPONSORSHIP", .Caption = "Only include unsponsored", .DefaultValueText = "Fields!ISSOLESPONSORSHIP"})
        _sponsorshipopportunityidproject.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "SPONSORSHIPOPPORTUNITYGROUPID", .ReadOnly = True})
        _sponsorshipopportunityidproject.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "CORRESPONDINGSPONSORID", .Hidden = True, .DefaultValueText = "Fields!SPONSORSHIPCONSTITUENTID"})
        _sponsorshipopportunityidproject.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "FINANCIALSPONSORID", .Hidden = True, .DefaultValueText = "Fields!REVENUECONSTITUENTID"})
        Me.Fields.Add(_sponsorshipopportunityidproject)

        '
        '_issolesponsorship
        '
        _issolesponsorship.Name = "ISSOLESPONSORSHIP"
        _issolesponsorship.Caption = "Sole sponsorship"
        Me.Fields.Add(_issolesponsorship)
        '
        '_startdate
        '
        _startdate.Name = "STARTDATE"
        _startdate.Caption = "Start date"
        _startdate.Required = True
        Me.Fields.Add(_startdate)
        '
        '_amount
        '
        _amount.Name = "AMOUNT"
        _amount.Caption = "Amount"
        _amount.Required = True
        _amount.CurrencyFieldId = "TRANSACTIONCURRENCYID"
        Me.Fields.Add(_amount)
        '
        '_autopay
        '
        _autopay.Name = "AUTOPAY"
        _autopay.Caption = "Pay installments automatically by:"
        _autopay.Value = True
        Me.Fields.Add(_autopay)
        '
        '_paymentmethodcode
        '
        _paymentmethodcode.Name = "PAYMENTMETHODCODE"
        _paymentmethodcode.Caption = "Payment method"
        _paymentmethodcode.Required = True
        _paymentmethodcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of PAYMENTMETHODCODES) With {.Value = PAYMENTMETHODCODES.[CreditCard], .Translation = "Credit card"})
        _paymentmethodcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of PAYMENTMETHODCODES) With {.Value = PAYMENTMETHODCODES.[DirectDebit], .Translation = "Direct debit"})
        _paymentmethodcode.Value = PAYMENTMETHODCODES.[CreditCard]
        Me.Fields.Add(_paymentmethodcode)
        '
        '_constituentaccountid
        '
        _constituentaccountid.Name = "CONSTITUENTACCOUNTID"
        _constituentaccountid.Caption = "Account"
        _constituentaccountid.SimpleDataListID = New Guid("0dd77a47-21b4-4953-abac-190e313b2d32")
        _constituentaccountid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("CONSTITUENTID", "Fields!REVENUECONSTITUENTID"))
        _constituentaccountid.LinkedActions.Add(_constituentaccountidaddaccountaction)
        Me.Fields.Add(_constituentaccountid)
        '
        '_constituentaccountidaddaccountaction
        '
        _constituentaccountidaddaccountaction.Name = "CONSTITUENTACCOUNTIDADDACCOUNTACTION"
        _constituentaccountidaddaccountaction.Caption = "Add account"
        _constituentaccountidaddaccountaction.DataFormInstanceID = New Guid("87c4e1ae-2ff3-48e0-9a74-874d39ded3ac")
        _constituentaccountidaddaccountaction.ContextIdDefinition = "Fields!SPONSORSHIPCONSTITUENTID"
        Me.Actions.Add(_constituentaccountidaddaccountaction)
        '
        '_referencenumber
        '
        _referencenumber.Name = "REFERENCENUMBER"
        _referencenumber.Caption = "Reference no."
        _referencenumber.MaxLength = 20
        Me.Fields.Add(_referencenumber)
        '
        '_referencedate
        '
        _referencedate.Name = "REFERENCEDATE"
        _referencedate.Caption = "Reference date"
        Me.Fields.Add(_referencedate)
        '
        '_frequencycode
        '
        _frequencycode.Name = "FREQUENCYCODE"
        _frequencycode.Caption = "Frequency"
        _frequencycode.Required = True
        _frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Annually], .Translation = "Annually"})
        _frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[SemiAnnually], .Translation = "Semi-annually"})
        _frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Quarterly], .Translation = "Quarterly"})
        _frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Bimonthly], .Translation = "Bimonthly"})
        _frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Monthly], .Translation = "Monthly"})
        _frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[SemiMonthly], .Translation = "Semi-monthly"})
        _frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Biweekly], .Translation = "Biweekly"})
        _frequencycode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FREQUENCYCODES) With {.Value = FREQUENCYCODES.[Weekly], .Translation = "Weekly"})
        _frequencycode.Value = FREQUENCYCODES.[Monthly]
        Me.Fields.Add(_frequencycode)
        '
        '_revenueschedulestartdate
        '
        _revenueschedulestartdate.Name = "REVENUESCHEDULESTARTDATE"
        _revenueschedulestartdate.Caption = "Starting on"
        _revenueschedulestartdate.Required = True
        Me.Fields.Add(_revenueschedulestartdate)
        '
        '_revenuescheduleenddate
        '
        _revenuescheduleenddate.Name = "REVENUESCHEDULEENDDATE"
        _revenuescheduleenddate.Caption = "Ending on"
        Me.Fields.Add(_revenuescheduleenddate)
        '
        '_creditcardnumber
        '
        _creditcardnumber.Name = "CREDITCARDNUMBER"
        _creditcardnumber.Caption = "Card number"
        _creditcardnumber.MaxLength = 20
        Me.Fields.Add(_creditcardnumber)
        '
        '_cardholdername
        '
        _cardholdername.Name = "CARDHOLDERNAME"
        _cardholdername.Caption = "Name on card"
        _cardholdername.MaxLength = 255
        Me.Fields.Add(_cardholdername)
        '
        '_expireson
        '
        _expireson.Name = "EXPIRESON"
        _expireson.Caption = "Expires on"
        Me.Fields.Add(_expireson)
        '
        '_creditcardtoken
        '
        _creditcardtoken.Name = "CREDITCARDTOKEN"
        _creditcardtoken.Caption = "CREDITCARDTOKEN"
        _creditcardtoken.CardNumberField = "CREDITCARDNUMBER"
        _creditcardtoken.CardHolderField = "CARDHOLDERNAME"
        _creditcardtoken.ExpirationDateField = "EXPIRESON"
        _creditcardtoken.CardTypeField = "CREDITTYPECODEID"
        Me.Fields.Add(_creditcardtoken)
        '
        '_credittypecodeid
        '
        _credittypecodeid.Name = "CREDITTYPECODEID"
        _credittypecodeid.Caption = "Card type"
        _credittypecodeid.CodeTableName = "CREDITTYPECODE"
        Me.Fields.Add(_credittypecodeid)
        '
        '_reservedopportunityidchild
        '
        _reservedopportunityidchild.Name = "RESERVEDOPPORTUNITYIDCHILD"
        _reservedopportunityidchild.Caption = "Child"
        _reservedopportunityidchild.SearchListID = New Guid("ab076868-114a-4696-afe9-8d590677708c")
        _reservedopportunityidchild.EnableQuickFind = True
        _reservedopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "SPONSORSHIPPROGRAMID", .ReadOnly = True, .DefaultValueText = "Fields!SPONSORSHIPPROGRAMID"})
        _reservedopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "ELIGIBILITYCODE", .ReadOnly = True, .DefaultValueText = "1"})
        _reservedopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "AVAILABILITYCODE", .ReadOnly = True, .DefaultValueText = "1"})
        _reservedopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RESTRICTFORSOLESPONSORSHIP", .Caption = "Only include unsponsored", .DefaultValueText = "Fields!ISSOLESPONSORSHIP"})
        _reservedopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "SPONSORSHIPOPPORTUNITYGROUPID", .ReadOnly = True})
        _reservedopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RESERVATIONKEYID", .ReadOnly = True, .DefaultValueText = "Fields!RESERVATIONKEY"})
        _reservedopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "CORRESPONDINGSPONSORID", .Hidden = True, .DefaultValueText = "Fields!SPONSORSHIPCONSTITUENTID"})
        _reservedopportunityidchild.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "FINANCIALSPONSORID", .Hidden = True, .DefaultValueText = "Fields!REVENUECONSTITUENTID"})
        Me.Fields.Add(_reservedopportunityidchild)
        '
        '_reservationkey
        '
        _reservationkey.Name = "RESERVATIONKEY"
        _reservationkey.Caption = "Reservation key"
        _reservationkey.SearchListID = New Guid("617890dc-3770-4505-b963-b6072cadced7")
        _reservationkey.EnableQuickFind = True
        _reservationkey.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "INCLUDEINACTIVE", .ReadOnly = True, .DefaultValueText = "0"})
        Me.Fields.Add(_reservationkey)
        '
        '_matchedopportunityid
        '
        _matchedopportunityid.Name = "MATCHEDOPPORTUNITYID"
        _matchedopportunityid.Caption = "MATCHEDOPPORTUNITYID"
        _matchedopportunityid.Visible = False
        Me.Fields.Add(_matchedopportunityid)
        '
        '_sendreminder
        '
        _sendreminder.Name = "SENDREMINDER"
        _sendreminder.Caption = "Send reminders"
        _sendreminder.Value = True
        Me.Fields.Add(_sendreminder)
        '
        '_findernumber
        '
        _findernumber.Name = "FINDERNUMBER"
        _findernumber.Caption = "Finder number"
        _findernumber.DoNotApplyFormat = True
        Me.Fields.Add(_findernumber)
        '
        '_sourcecode
        '
        _sourcecode.Name = "SOURCECODE"
        _sourcecode.Caption = "Source code"
        _sourcecode.MaxLength = 50
        Me.Fields.Add(_sourcecode)
        '
        '_appealid
        '
        _appealid.Name = "APPEALID"
        _appealid.Caption = "Appeal"
        _appealid.SearchListID = New Guid("7d004826-2a51-4938-9f14-4eda9dade2df")
        _appealid.EnableQuickFind = True
        _appealid.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("2736a8b5-ab2e-4330-ba15-98818321c643"), "Add"))
        Me.Fields.Add(_appealid)
        '
        '_mailingid
        '
        _mailingid.Name = "MAILINGID"
        _mailingid.Caption = "Mailing"
        _mailingid.SearchListID = New Guid("349397cb-e2dd-43e8-a4ca-af5647c91d99")
        _mailingid.EnableQuickFind = True
        _mailingid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "STATUS", .Caption = "Status", .Hidden = True, .ReadOnly = True, .DefaultValueText = "1"})
        _mailingid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "INCLUDEAPPEALMAILINGS", .Caption = "Include appeal mailings", .Hidden = True, .ReadOnly = True, .DefaultValueText = "true"})
        Me.Fields.Add(_mailingid)
        '
        '_channelcodeid
        '
        _channelcodeid.Name = "CHANNELCODEID"
        _channelcodeid.Caption = "Inbound channel"
        _channelcodeid.CodeTableName = "CHANNELCODE"
        Me.Fields.Add(_channelcodeid)
        '
        '_reference
        '
        _reference.Name = "REFERENCE"
        _reference.Caption = "Reference"
        _reference.MaxLength = 255
        _reference.AllowZoom = True
        Me.Fields.Add(_reference)
        '
        '_categorycodeid
        '
        _categorycodeid.Name = "CATEGORYCODEID"
        _categorycodeid.Caption = "Revenue category"
        _categorycodeid.SimpleDataListID = New Guid("d9dd46ce-6651-4fcc-b9fe-e59162662224")
        Me.Fields.Add(_categorycodeid)
        '
        '_expirationreasonid
        '
        _expirationreasonid.Name = "EXPIRATIONREASONID"
        _expirationreasonid.Caption = "Reason"
        _expirationreasonid.SimpleDataListID = New Guid("c8d3128e-a2eb-4413-b0b4-1585ad5bf001")
        _expirationreasonid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPE", "11"))
        Me.Fields.Add(_expirationreasonid)
        '
        '_transactioncurrencyid
        '
        _transactioncurrencyid.Name = "TRANSACTIONCURRENCYID"
        _transactioncurrencyid.Caption = "Transaction currency"
        _transactioncurrencyid.SimpleDataListID = New Guid("40bf0d4a-5e78-46f4-ab50-56d508e35516")
        Me.Fields.Add(_transactioncurrencyid)
        '
        '_baseexchangerateid
        '
        _baseexchangerateid.Name = "BASEEXCHANGERATEID"
        _baseexchangerateid.Caption = "Exchange rate"
        _baseexchangerateid.SimpleDataListID = New Guid("c254b16d-ba67-4431-9f7e-ab7f75f4f246")
        _baseexchangerateid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("FROMCURRENCYID", "Fields!TRANSACTIONCURRENCYID"))
        _baseexchangerateid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TOCURRENCYID", "Fields!BASECURRENCYID"))
        _baseexchangerateid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPECODE", "1"))
        _baseexchangerateid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("ASOFDATE", "Fields!DATE"))
        _baseexchangerateid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("INCLUDESPOTRATE", "1"))
        _baseexchangerateid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("CURRENTEXCHANGERATEID", "Fields!BASEEXCHANGERATEID"))
        Me.Fields.Add(_baseexchangerateid)
        '
        '_exchangerate
        '
        _exchangerate.Name = "EXCHANGERATE"
        _exchangerate.Caption = "Exchange rate"
        _exchangerate.Precision = 20
        _exchangerate.Scale = 8
        Me.Fields.Add(_exchangerate)
        '
        '_basecurrencyid
        '
        _basecurrencyid.Name = "BASECURRENCYID"
        _basecurrencyid.Caption = "BASECURRENCYID"
        _basecurrencyid.Visible = False
        _basecurrencyid.DBReadOnly = True
        Me.Fields.Add(_basecurrencyid)
        '
        '_baseamount
        '
        _baseamount.Name = "BASEAMOUNT"
        _baseamount.Caption = "Base amount"
        _baseamount.DBReadOnly = True
        _baseamount.CurrencyFieldId = "BASECURRENCYID"
        Me.Fields.Add(_baseamount)
        '
        '_basecurrencydecimaldigits
        '
        _basecurrencydecimaldigits.Name = "BASECURRENCYDECIMALDIGITS"
        _basecurrencydecimaldigits.Caption = "Base currency decimal digits"
        _basecurrencydecimaldigits.Visible = False
        _basecurrencydecimaldigits.DBReadOnly = True
        Me.Fields.Add(_basecurrencydecimaldigits)
        '
        '_basecurrencyroundingtypecode
        '
        _basecurrencyroundingtypecode.Name = "BASECURRENCYROUNDINGTYPECODE"
        _basecurrencyroundingtypecode.Caption = "Base currency rounding type code"
        _basecurrencyroundingtypecode.Visible = False
        _basecurrencyroundingtypecode.DBReadOnly = True
        Me.Fields.Add(_basecurrencyroundingtypecode)
        '
        '_batchnumber
        '
        _batchnumber.Name = "BATCHNUMBER"
        _batchnumber.Caption = "BATCHNUMBER"
        _batchnumber.Visible = False
        _batchnumber.MaxLength = 100
        Me.Fields.Add(_batchnumber)
        '
        '_revenuedevelopmentfunctioncodeid
        '
        _revenuedevelopmentfunctioncodeid.Name = "REVENUEDEVELOPMENTFUNCTIONCODEID"
        _revenuedevelopmentfunctioncodeid.Caption = "Revenue function"
        _revenuedevelopmentfunctioncodeid.Visible = False
        _revenuedevelopmentfunctioncodeid.DBReadOnly = True
        _revenuedevelopmentfunctioncodeid.CodeTableName = "REVENUEDEVELOPMENTFUNCTIONCODE"
        Me.Fields.Add(_revenuedevelopmentfunctioncodeid)
        '
        '_donotacknowledge
        '
        _donotacknowledge.Name = "DONOTACKNOWLEDGE"
        _donotacknowledge.Caption = "Do not acknowledge"
        Me.Fields.Add(_donotacknowledge)
        '
        '_selectopportunityid
        '
        _selectopportunityid.Name = "SELECTOPPORTUNITYID"
        _selectopportunityid.Caption = "Select Opportunity"
        _selectopportunityid.DBReadOnly = True
        _selectopportunityid.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of SELECTOPPORTUNITYIDS)) With {.Value = SELECTOPPORTUNITYIDS.[ChooseASpecificOpportunity], .Translation = "Choose a specific opportunity"})
        _selectopportunityid.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of SELECTOPPORTUNITYIDS)) With {.Value = SELECTOPPORTUNITYIDS.[ChooseAReservedOpportunity], .Translation = "Choose a reserved opportunity"})
        _selectopportunityid.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of SELECTOPPORTUNITYIDS)) With {.Value = SELECTOPPORTUNITYIDS.[FindAMatchingOpportunityOfGreatestNeed], .Translation = "Find a matching opportunity of greatest need"})
        _selectopportunityid.Value = SELECTOPPORTUNITYIDS.[FindAMatchingOpportunityOfGreatestNeed]
        Me.Fields.Add(_selectopportunityid)
        '
        '_isfixedtermsponsorship
        '
        _isfixedtermsponsorship.Name = "ISFIXEDTERMSPONSORSHIP"
        _isfixedtermsponsorship.Caption = "This is a fixed-term sponsorship"
        _isfixedtermsponsorship.DBReadOnly = True
        Me.Fields.Add(_isfixedtermsponsorship)
        '
        '_rgschedule
        '
        _rgschedule.Name = "RGSCHEDULE"
        _rgschedule.Caption = "RGSCHEDULE"
        _rgschedule.DBReadOnly = True
        Me.Fields.Add(_rgschedule)
        '
        '_mopportunityname
        '
        _mopportunityname.Name = "MOPPORTUNITYNAME"
        _mopportunityname.Caption = "Name"
        _mopportunityname.DBReadOnly = True
        Me.Fields.Add(_mopportunityname)
        '
        '_mopportunitylocation
        '
        _mopportunitylocation.Name = "MOPPORTUNITYLOCATION"
        _mopportunitylocation.Caption = "Location"
        _mopportunitylocation.DBReadOnly = True
        Me.Fields.Add(_mopportunitylocation)
        '
        '_mopportunitylookupid
        '
        _mopportunitylookupid.Name = "MOPPORTUNITYLOOKUPID"
        _mopportunitylookupid.Caption = "Lookup ID"
        _mopportunitylookupid.DBReadOnly = True
        Me.Fields.Add(_mopportunitylookupid)
        '
        '_mopportunitygender
        '
        _mopportunitygender.Name = "MOPPORTUNITYGENDER"
        _mopportunitygender.Caption = "Gender"
        _mopportunitygender.DBReadOnly = True
        Me.Fields.Add(_mopportunitygender)
        '
        '_mopportunitybirthdate
        '
        _mopportunitybirthdate.Name = "MOPPORTUNITYBIRTHDATE"
        _mopportunitybirthdate.Caption = "Birthdate"
        _mopportunitybirthdate.DBReadOnly = True
        Me.Fields.Add(_mopportunitybirthdate)
        '
        '_mopportunityimage
        '
        _mopportunityimage.Name = "MOPPORTUNITYIMAGE"
        _mopportunityimage.Caption = "MOPPORTUNITYIMAGE"
        _mopportunityimage.Visible = False
        _mopportunityimage.DBReadOnly = True
        Me.Fields.Add(_mopportunityimage)
        '
        '_findernumberstring
        '
        _findernumberstring.Name = "FINDERNUMBERSTRING"
        _findernumberstring.Caption = "Finder number"
        _findernumberstring.DBReadOnly = True
        Me.Fields.Add(_findernumberstring)
        '
        '_invalidfindernumberimage
        '
        _invalidfindernumberimage.Name = "INVALIDFINDERNUMBERIMAGE"
        _invalidfindernumberimage.Caption = "Invalid finder number"
        _invalidfindernumberimage.DBReadOnly = True
        Me.Fields.Add(_invalidfindernumberimage)
        '
        '_installments
        '
        _installments.Name = "INSTALLMENTS"
        _installments.Caption = "INSTALLMENTS"
        _installments.DBReadOnly = True
        Me.Fields.Add(_installments)
        '
        '_generalinformation
        '
        _generalinformation.Name = "GENERALINFORMATION"
        _generalinformation.Caption = "General"
        _generalinformation.Fields.Add("REVENUECONSTITUENTID")
        _generalinformation.Fields.Add("FINDERNUMBER")
        _generalinformation.Fields.Add("GIFTRECIPIENT")
        _generalinformation.Fields.Add("SPONSORSHIPCONSTITUENTID")
        _generalinformation.Fields.Add("SPONSORSHIPPROGRAMID")
        _generalinformation.Fields.Add("STARTDATE")
        _generalinformation.Fields.Add("SPONSORSHIPREASONID")
        Me.Fields.Add(_generalinformation)
        '
        '_sponsorshipopportunity
        '
        _sponsorshipopportunity.Name = "SPONSORSHIPOPPORTUNITY"
        _sponsorshipopportunity.Caption = "Sponsorship Opportunity"
        _sponsorshipopportunity.Fields.Add("CHILDREN")
        _sponsorshipopportunity.Fields.Add("SPONSORSHIPOPPORTUNITYIDCHILD")
        _sponsorshipopportunity.Fields.Add("SPONSORSHIPOPPORTUNITYIDPROJECT")
        _sponsorshipopportunity.Fields.Add("RESERVATIONKEY")
        _sponsorshipopportunity.Fields.Add("RESERVEDOPPORTUNITYIDCHILD")
        _sponsorshipopportunity.Fields.Add("SPONSORSHIPLOCATIONID")
        _sponsorshipopportunity.Fields.Add("GENDERCODE")
        _sponsorshipopportunity.Fields.Add("SPROPPAGERANGEID")
        _sponsorshipopportunity.Fields.Add("ISORPHANEDCODE")
        _sponsorshipopportunity.Fields.Add("ISHIVPOSITIVECODE")
        _sponsorshipopportunity.Fields.Add("HASCONDITIONCODE")
        _sponsorshipopportunity.Fields.Add("SPROPPPROJECTCATEGORYCODEID")
        _sponsorshipopportunity.Fields.Add("ISSOLESPONSORSHIP")
        Me.Fields.Add(_sponsorshipopportunity)
        '
        '_paymentschedule
        '
        _paymentschedule.Name = "PAYMENTSCHEDULE"
        _paymentschedule.Caption = "Schedule"
        _paymentschedule.Fields.Add("FREQUENCYCODE")
        _paymentschedule.Fields.Add("REVENUESCHEDULESTARTDATE")
        _paymentschedule.Fields.Add("REVENUESCHEDULEENDDATE")
        _paymentschedule.Fields.Add("RGSCHEDULE")
        Me.Fields.Add(_paymentschedule)
        '
        '_paymentinformation
        '
        _paymentinformation.Name = "PAYMENTINFORMATION"
        _paymentinformation.Caption = "Payment information"
        _paymentinformation.Fields.Add("AUTOPAY")
        _paymentinformation.Fields.Add("PAYMENTMETHODCODE")
        _paymentinformation.Fields.Add("CREDITTYPECODEID")
        _paymentinformation.Fields.Add("REFERENCENUMBER")
        _paymentinformation.Fields.Add("CONSTITUENTACCOUNTID")
        _paymentinformation.Fields.Add("EXPIRESON")
        Me.Fields.Add(_paymentinformation)
        '
        '_matchedopportunity
        '
        _matchedopportunity.Name = "MATCHEDOPPORTUNITY"
        _matchedopportunity.Caption = "Matched opportunity"
        _matchedopportunity.Fields.Add("MOPPORTUNITYNAME")
        _matchedopportunity.Fields.Add("MOPPORTUNITYLOCATION")
        _matchedopportunity.Fields.Add("MOPPORTUNITYLOOKUPID")
        _matchedopportunity.Fields.Add("MOPPORTUNITYGENDER")
        _matchedopportunity.Fields.Add("MOPPORTUNITYBIRTHDATE")
        Me.Fields.Add(_matchedopportunity)
        '
        '_tabsponsorship
        '
        _tabsponsorship.Name = "TAB_SPONSORSHIP"
        _tabsponsorship.Caption = "Sponsorship"
        Me.Fields.Add(_tabsponsorship)
        '
        '_tabpayment
        '
        _tabpayment.Name = "TAB_PAYMENT"
        _tabpayment.Caption = "Payment"
        Me.Fields.Add(_tabpayment)
        '
        '_tabexpiration
        '
        _tabexpiration.Name = "TAB_EXPIRATION"
        _tabexpiration.Caption = "Expiration"
        Me.Fields.Add(_tabexpiration)
        '
        '_findopportunity
        '
        _findopportunity.Name = "FINDOPPORTUNITY"
        _findopportunity.Caption = "Find"
		Me.Actions.Add(_findopportunity)
		'
		'_clearsearchaction
		'
		_clearsearchaction.Name = "CLEARSEARCHACTION"
		_clearsearchaction.Caption = "Clear"
		Me.Actions.Add(_clearsearchaction)
        '
        '_removeselectedchild
        '
        _removeselectedchild.Name = "REMOVESELECTEDCHILD"
        _removeselectedchild.Caption = "Remove"
        Me.Actions.Add(_removeselectedchild)
        '
        ' _addselectedchild 
        '
        _addselectedchild.Name = "ADDSELECTEDCHILD"
        _addselectedchild.Caption = "Add Child"
        Me.Actions.Add(_addselectedchild)
        '
        '_sourcecodelookup
        '
        _sourcecodelookup.Name = "SOURCECODELOOKUP"
        _sourcecodelookup.Caption = ""
        _sourcecodelookup.Description = "Look up a source code to associate with this gift"
        _sourcecodelookup.ImageKey = "RES:findsmall"
        _sourcecodelookup.SearchListId = New Guid("ef764bb7-fdf0-45c2-a50f-294bf460f200")
        Me.Actions.Add(_sourcecodelookup)
        '
        '_currencyaction
        '
        _currencyaction.Name = "CURRENCYACTION"
        _currencyaction.Caption = ""
        _currencyaction.Description = "Edit the currency and exchange rate information for this pledge"
        _currencyaction.ImageKey = "catalog:Blackbaud.AppFx.Currency.Catalog.dll,Blackbaud.AppFx.Currency.Catalog.multicurrency_16.png"
        _currencyaction.ModelAssemblyName = "Blackbaud.AppFx.Fundraising.UIModel.dll"
        _currencyaction.ModelClassName = "Blackbaud.AppFx.Fundraising.UIModel.CurrencyFormUIModel"
        Me.Actions.Add(_currencyaction)

        OnCreated()

    End Sub

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FORMTITLE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _formtitle
        End Get
    End Property

    ''' <summary>
    ''' Financial sponsor
    ''' </summary>
    <System.ComponentModel.Description("Financial sponsor")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REVENUECONSTITUENTID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _revenueconstituentid
        End Get
    End Property

    ''' <summary>
    ''' Gift
    ''' </summary>
    <System.ComponentModel.Description("Gift")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [GIFTRECIPIENT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _giftrecipient
        End Get
    End Property

    ''' <summary>
    ''' Corresponding sponsor
    ''' </summary>
    <System.ComponentModel.Description("Corresponding sponsor")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPCONSTITUENTID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _sponsorshipconstituentid
        End Get
    End Property

    ''' <summary>
    ''' Reason
    ''' </summary>
    <System.ComponentModel.Description("Reason")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPREASONID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _sponsorshipreasonid
        End Get
    End Property

    ''' <summary>
    ''' Program
    ''' </summary>
    <System.ComponentModel.Description("Program")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPPROGRAMID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _sponsorshipprogramid
        End Get
    End Property

    ''' <summary>
    ''' Children
    ''' </summary>
    <System.ComponentModel.Description("Children")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CHILDREN]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of SponsorshipAddFormWrappedCHILDRENUIModel)
        Get
            Return _children
        End Get
    End Property

    ''' <summary>
    ''' Expiration date
    ''' </summary>
    <System.ComponentModel.Description("Expiration date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PLANNEDENDDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _plannedenddate
        End Get
    End Property

    ''' <summary>
    ''' Location
    ''' </summary>
    <System.ComponentModel.Description("Location")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPLOCATIONID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _sponsorshiplocationid
        End Get
    End Property

    ''' <summary>
    ''' Age range
    ''' </summary>
    <System.ComponentModel.Description("Age range")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPROPPAGERANGEID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _sproppagerangeid
        End Get
    End Property

    ''' <summary>
    ''' Gender
    ''' </summary>
    <System.ComponentModel.Description("Gender")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [GENDERCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of GENDERCODES))
        Get
            Return _gendercode
        End Get
    End Property

    ''' <summary>
    ''' HIV positive
    ''' </summary>
    <System.ComponentModel.Description("HIV positive")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ISHIVPOSITIVECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISHIVPOSITIVECODES))
        Get
            Return _ishivpositivecode
        End Get
    End Property

    ''' <summary>
    ''' Disability/Illness
    ''' </summary>
    <System.ComponentModel.Description("Disability/Illness")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [HASCONDITIONCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of HASCONDITIONCODES))
        Get
            Return _hasconditioncode
        End Get
    End Property

    ''' <summary>
    ''' Orphaned
    ''' </summary>
    <System.ComponentModel.Description("Orphaned")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ISORPHANEDCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISORPHANEDCODES))
        Get
            Return _isorphanedcode
        End Get
    End Property

    ''' <summary>
    ''' Category
    ''' </summary>
    <System.ComponentModel.Description("Category")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPROPPPROJECTCATEGORYCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _sproppprojectcategorycodeid
        End Get
    End Property

    ''' <summary>
    ''' Child
    ''' </summary>
    <System.ComponentModel.Description("Child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYIDCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _sponsorshipopportunityidchild
        End Get
    End Property

    ''' <summary>
    ''' Project
    ''' </summary>
    <System.ComponentModel.Description("Project")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYIDPROJECT]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _sponsorshipopportunityidproject
        End Get
    End Property

    ''' <summary>
    ''' Sole sponsorship
    ''' </summary>
    <System.ComponentModel.Description("Sole sponsorship")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ISSOLESPONSORSHIP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _issolesponsorship
        End Get
    End Property

    ''' <summary>
    ''' Start date
    ''' </summary>
    <System.ComponentModel.Description("Start date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [STARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _startdate
        End Get
    End Property

    ''' <summary>
    ''' Amount
    ''' </summary>
    <System.ComponentModel.Description("Amount")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [AMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _amount
        End Get
    End Property

    ''' <summary>
    ''' Pay installments automatically by
    ''' </summary>
    <System.ComponentModel.Description("Pay installments automatically by")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [AUTOPAY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _autopay
        End Get
    End Property

    ''' <summary>
    ''' Payment method
    ''' </summary>
    <System.ComponentModel.Description("Payment method")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PAYMENTMETHODCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of PAYMENTMETHODCODES)
        Get
            Return _paymentmethodcode
        End Get
    End Property

    ''' <summary>
    ''' Account
    ''' </summary>
    <System.ComponentModel.Description("Account")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CONSTITUENTACCOUNTID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _constituentaccountid
        End Get
    End Property

    ''' <summary>
    ''' Add account
    ''' </summary>
    <System.ComponentModel.Description("Add account")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CONSTITUENTACCOUNTIDADDACCOUNTACTION]() As Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction
        Get
            Return _constituentaccountidaddaccountaction
        End Get
    End Property

    ''' <summary>
    ''' Reference no.
    ''' </summary>
    <System.ComponentModel.Description("Reference no.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REFERENCENUMBER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _referencenumber
        End Get
    End Property

    ''' <summary>
    ''' Reference date
    ''' </summary>
    <System.ComponentModel.Description("Reference date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REFERENCEDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.FuzzyDateField
        Get
            Return _referencedate
        End Get
    End Property

    ''' <summary>
    ''' Frequency
    ''' </summary>
    <System.ComponentModel.Description("Frequency")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FREQUENCYCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of FREQUENCYCODES)
        Get
            Return _frequencycode
        End Get
    End Property

    ''' <summary>
    ''' Starting on
    ''' </summary>
    <System.ComponentModel.Description("Starting on")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REVENUESCHEDULESTARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _revenueschedulestartdate
        End Get
    End Property

    ''' <summary>
    ''' Ending on
    ''' </summary>
    <System.ComponentModel.Description("Ending on")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REVENUESCHEDULEENDDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _revenuescheduleenddate
        End Get
    End Property

    ''' <summary>
    ''' Card number
    ''' </summary>
    <System.ComponentModel.Description("Card number")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CREDITCARDNUMBER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _creditcardnumber
        End Get
    End Property

    ''' <summary>
    ''' Name on card
    ''' </summary>
    <System.ComponentModel.Description("Name on card")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CARDHOLDERNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _cardholdername
        End Get
    End Property

    ''' <summary>
    ''' Expires on
    ''' </summary>
    <System.ComponentModel.Description("Expires on")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [EXPIRESON]() As Global.Blackbaud.AppFx.UIModeling.Core.FuzzyDateField
        Get
            Return _expireson
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CREDITCARDTOKEN]() As Global.Blackbaud.AppFx.UIModeling.Core.CreditCardTokenField
        Get
            Return _creditcardtoken
        End Get
    End Property

    ''' <summary>
    ''' Card type
    ''' </summary>
    <System.ComponentModel.Description("Card type")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CREDITTYPECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _credittypecodeid
        End Get
    End Property

    ''' <summary>
    ''' Child
    ''' </summary>
    <System.ComponentModel.Description("Child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RESERVEDOPPORTUNITYIDCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _reservedopportunityidchild
        End Get
    End Property

    ''' <summary>
    ''' Reservation key
    ''' </summary>
    <System.ComponentModel.Description("Reservation key")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RESERVATIONKEY]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _reservationkey
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MATCHEDOPPORTUNITYID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _matchedopportunityid
        End Get
    End Property

    ''' <summary>
    ''' Send reminders
    ''' </summary>
    <System.ComponentModel.Description("Send reminders")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SENDREMINDER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _sendreminder
        End Get
    End Property

    ''' <summary>
    ''' Finder number
    ''' </summary>
    <System.ComponentModel.Description("Finder number")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FINDERNUMBER]() As Global.Blackbaud.AppFx.UIModeling.Core.LongField
        Get
            Return _findernumber
        End Get
    End Property

    ''' <summary>
    ''' Source code
    ''' </summary>
    <System.ComponentModel.Description("Source code")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SOURCECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _sourcecode
        End Get
    End Property

    ''' <summary>
    ''' Appeal
    ''' </summary>
    <System.ComponentModel.Description("Appeal")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPEALID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _appealid
        End Get
    End Property

    ''' <summary>
    ''' Mailing
    ''' </summary>
    <System.ComponentModel.Description("Mailing")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MAILINGID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _mailingid
        End Get
    End Property

    ''' <summary>
    ''' Inbound channel
    ''' </summary>
    <System.ComponentModel.Description("Inbound channel")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CHANNELCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _channelcodeid
        End Get
    End Property

    ''' <summary>
    ''' Reference
    ''' </summary>
    <System.ComponentModel.Description("Reference")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REFERENCE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _reference
        End Get
    End Property

    ''' <summary>
    ''' Revenue category
    ''' </summary>
    <System.ComponentModel.Description("Revenue category")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CATEGORYCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _categorycodeid
        End Get
    End Property

    ''' <summary>
    ''' Reason
    ''' </summary>
    <System.ComponentModel.Description("Reason")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [EXPIRATIONREASONID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _expirationreasonid
        End Get
    End Property

    ''' <summary>
    ''' Transaction currency
    ''' </summary>
    <System.ComponentModel.Description("Transaction currency")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [TRANSACTIONCURRENCYID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _transactioncurrencyid
        End Get
    End Property

    ''' <summary>
    ''' Exchange rate
    ''' </summary>
    <System.ComponentModel.Description("Exchange rate")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BASEEXCHANGERATEID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _baseexchangerateid
        End Get
    End Property

    ''' <summary>
    ''' Exchange rate
    ''' </summary>
    <System.ComponentModel.Description("Exchange rate")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [EXCHANGERATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        Get
            Return _exchangerate
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BASECURRENCYID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _basecurrencyid
        End Get
    End Property

    ''' <summary>
    ''' Base amount
    ''' </summary>
    <System.ComponentModel.Description("Base amount")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BASEAMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _baseamount
        End Get
    End Property

    ''' <summary>
    ''' Base currency decimal digits
    ''' </summary>
    <System.ComponentModel.Description("Base currency decimal digits")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BASECURRENCYDECIMALDIGITS]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _basecurrencydecimaldigits
        End Get
    End Property

    ''' <summary>
    ''' Base currency rounding type code
    ''' </summary>
    <System.ComponentModel.Description("Base currency rounding type code")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BASECURRENCYROUNDINGTYPECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _basecurrencyroundingtypecode
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BATCHNUMBER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _batchnumber
        End Get
    End Property

    ''' <summary>
    ''' Revenue function
    ''' </summary>
    <System.ComponentModel.Description("Revenue function")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REVENUEDEVELOPMENTFUNCTIONCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _revenuedevelopmentfunctioncodeid
        End Get
    End Property

    ''' <summary>
    ''' Do not acknowledge
    ''' </summary>
    <System.ComponentModel.Description("Do not acknowledge")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DONOTACKNOWLEDGE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _donotacknowledge
        End Get
    End Property

    ''' <summary>
    ''' Select Opportunity
    ''' </summary>
    <System.ComponentModel.Description("Select Opportunity")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SELECTOPPORTUNITYID]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of SELECTOPPORTUNITYIDS))
        Get
            Return _selectopportunityid
        End Get
    End Property

    ''' <summary>
    ''' This is a fixed-term sponsorship
    ''' </summary>
    <System.ComponentModel.Description("This is a fixed-term sponsorship")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ISFIXEDTERMSPONSORSHIP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isfixedtermsponsorship
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RGSCHEDULE]() As Global.Blackbaud.AppFx.UIModeling.Core.XMLField
        Get
            Return _rgschedule
        End Get
    End Property

    ''' <summary>
    ''' Name
    ''' </summary>
    <System.ComponentModel.Description("Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MOPPORTUNITYNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _mopportunityname
        End Get
    End Property

    ''' <summary>
    ''' Location
    ''' </summary>
    <System.ComponentModel.Description("Location")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MOPPORTUNITYLOCATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _mopportunitylocation
        End Get
    End Property

    ''' <summary>
    ''' Lookup ID
    ''' </summary>
    <System.ComponentModel.Description("Lookup ID")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MOPPORTUNITYLOOKUPID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _mopportunitylookupid
        End Get
    End Property

    ''' <summary>
    ''' Gender
    ''' </summary>
    <System.ComponentModel.Description("Gender")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MOPPORTUNITYGENDER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _mopportunitygender
        End Get
    End Property

    ''' <summary>
    ''' Birthdate
    ''' </summary>
    <System.ComponentModel.Description("Birthdate")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MOPPORTUNITYBIRTHDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _mopportunitybirthdate
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MOPPORTUNITYIMAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _mopportunityimage
        End Get
    End Property

    ''' <summary>
    ''' Finder number
    ''' </summary>
    <System.ComponentModel.Description("Finder number")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FINDERNUMBERSTRING]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _findernumberstring
        End Get
    End Property

    ''' <summary>
    ''' Invalid finder number
    ''' </summary>
    <System.ComponentModel.Description("Invalid finder number")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [INVALIDFINDERNUMBERIMAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _invalidfindernumberimage
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [INSTALLMENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of SponsorshipAddFormWrappedINSTALLMENTSUIModel)
        Get
            Return _installments
        End Get
    End Property

    ''' <summary>
    ''' General
    ''' </summary>
    <System.ComponentModel.Description("General")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [GENERALINFORMATION]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _generalinformation
        End Get
    End Property

    ''' <summary>
    ''' Sponsorship Opportunity
    ''' </summary>
    <System.ComponentModel.Description("Sponsorship Opportunity")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITY]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _sponsorshipopportunity
        End Get
    End Property

    ''' <summary>
    ''' Schedule
    ''' </summary>
    <System.ComponentModel.Description("Schedule")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PAYMENTSCHEDULE]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _paymentschedule
        End Get
    End Property

    ''' <summary>
    ''' Payment information
    ''' </summary>
    <System.ComponentModel.Description("Payment information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PAYMENTINFORMATION]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _paymentinformation
        End Get
    End Property

    ''' <summary>
    ''' Matched opportunity
    ''' </summary>
    <System.ComponentModel.Description("Matched opportunity")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MATCHEDOPPORTUNITY]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _matchedopportunity
        End Get
    End Property

    ''' <summary>
    ''' Sponsorship
    ''' </summary>
    <System.ComponentModel.Description("Sponsorship")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [TAB_SPONSORSHIP]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _tabsponsorship
        End Get
    End Property

    ''' <summary>
    ''' Payment
    ''' </summary>
    <System.ComponentModel.Description("Payment")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [TAB_PAYMENT]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _tabpayment
        End Get
    End Property

    ''' <summary>
    ''' Expiration
    ''' </summary>
    <System.ComponentModel.Description("Expiration")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [TAB_EXPIRATION]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _tabexpiration
        End Get
    End Property

    ''' <summary>
    ''' Find
    ''' </summary>
    <System.ComponentModel.Description("Find")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FINDOPPORTUNITY]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _findopportunity
        End Get
	End Property


	''' <summary>
	''' Clear
	''' </summary>
	<System.ComponentModel.Description("Clear")> _
 <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
 Public ReadOnly Property [CLEARSEARCHACTION]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
		Get
			Return _clearsearchaction
		End Get
	End Property


    ''' <summary>
    ''' Remove
    ''' </summary>
    <System.ComponentModel.Description("Remove")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REMOVESELECTEDCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _removeselectedchild
        End Get
    End Property
    ''' <summary>
    ''' Add Child
    ''' </summary>
    <System.ComponentModel.Description("Add Child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ADDSELECTEDCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _addselectedchild
        End Get
    End Property

    ''' <summary>
    ''' Look up a source code to associate with this gift
    ''' </summary>
    <System.ComponentModel.Description("Look up a source code to associate with this gift")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SOURCECODELOOKUP]() As Global.Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction
        Get
            Return _sourcecodelookup
        End Get
    End Property

    ''' <summary>
    ''' Edit the currency and exchange rate information for this pledge
    ''' </summary>
    <System.ComponentModel.Description("Edit the currency and exchange rate information for this pledge")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CURRENCYACTION]() As Global.Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction
        Get
            Return _currencyaction
        End Get
    End Property

    Private Sub SearchingForChild(ByVal sender As Object, ByVal e As SearchEventArgs)
        If True Then

        End If
    End Sub

End Class
