Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'View Sponsorship Details View Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "2ba9fc47-2104-4e17-835f-59b09b9ee85c", "2accdfea-fd90-4ba6-b0ee-9498368caa53", "Sponsorship")> _
Partial Public Class [ViewSponsorshipDetailsViewFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _sponsorshipid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _sponsorshipopportunityid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _revenuesplitid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _ismostrecentforcommitment As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _sponsorshipid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _sponsorshipopportunityid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _revenuesplitid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _ismostrecentforcommitment = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("2ba9fc47-2104-4e17-835f-59b09b9ee85c")
        MyBase.DataFormInstanceId = New Guid("2accdfea-fd90-4ba6-b0ee-9498368caa53")
        MyBase.RecordType = "Sponsorship"
        MyBase.FixedDialog = True
        MyBase.FORMHEADER.Value = "View Sponsorship Details"
		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ViewSponsorshipDetailsViewForm.html"

        '
        '_sponsorshipid
        '
        _sponsorshipid.Name = "SPONSORSHIPID"
        _sponsorshipid.Caption = "Sponsorship Id"
        _sponsorshipid.DBReadOnly = True
        Me.Fields.Add(_sponsorshipid)
        '
        '_sponsorshipopportunityid
        '
        _sponsorshipopportunityid.Name = "SPONSORSHIPOPPORTUNITYID"
        _sponsorshipopportunityid.Caption = "Sponsorshipopportunity ID"
        _sponsorshipopportunityid.DBReadOnly = True
        Me.Fields.Add(_sponsorshipopportunityid)
        '
        '_revenuesplitid
        '
        _revenuesplitid.Name = "REVENUESPLITID"
        _revenuesplitid.Caption = "Revenuesplit ID (financial transaction id)"
        _revenuesplitid.DBReadOnly = True
        Me.Fields.Add(_revenuesplitid)
        '
        '_ismostrecentforcommitment
        '
        _ismostrecentforcommitment.Name = "ISMOSTRECENTFORCOMMITMENT"
        _ismostrecentforcommitment.Caption = "Is most recent for commitment?"
        _ismostrecentforcommitment.DBReadOnly = True
        Me.Fields.Add(_ismostrecentforcommitment)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Sponsorship Id
    ''' </summary>
    <System.ComponentModel.Description("Sponsorship Id")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _sponsorshipid
        End Get
    End Property
    
    ''' <summary>
    ''' Sponsorshipopportunity ID
    ''' </summary>
    <System.ComponentModel.Description("Sponsorshipopportunity ID")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _sponsorshipopportunityid
        End Get
    End Property
    
    ''' <summary>
    ''' Revenuesplit ID (financial transaction id)
    ''' </summary>
    <System.ComponentModel.Description("Revenuesplit ID (financial transaction id)")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REVENUESPLITID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _revenuesplitid
        End Get
    End Property
    
    ''' <summary>
    ''' Is most recent for commitment?
    ''' </summary>
    <System.ComponentModel.Description("Is most recent for commitment?")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ISMOSTRECENTFORCOMMITMENT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _ismostrecentforcommitment
        End Get
    End Property
    
End Class
