Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Add Web Sponsorship OnBoarding Interactions' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "7fee7603-28c1-4eb0-b033-70607018198c", "ed807a08-e800-41c2-9e05-a6da01eb4493", "Interaction", "CONSTITUENT")> _
Partial Public Class [AddWebSponsorshipOnBoardingInteractionsUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _sponsorshipconstituentid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _isprospect As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _sponsorname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _interactiontypecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _pfmid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _filterdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _children As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of AddWebSponsorshipOnBoardingInteractionsCHILDRENUIModel)
	Private WithEvents _sponsorshipopportunityidchild As Global.Blackbaud.AppFx.UIModeling.Core.StringField
	Private WithEvents _findchildren As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
	Private WithEvents _addselectedchild As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
	Private WithEvents _removeselectedchild As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public Sub New()
		MyBase.New()

		_sponsorshipconstituentid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		_isprospect = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		_sponsorname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
		_interactiontypecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
		_pfmid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
		_filterdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
		_children = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of AddWebSponsorshipOnBoardingInteractionsCHILDRENUIModel)
		_sponsorshipopportunityidchild = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
		_findchildren = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
		_addselectedchild = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
		_removeselectedchild = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

		MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
		MyBase.DataFormTemplateId = New Guid("7fee7603-28c1-4eb0-b033-70607018198c")
		MyBase.DataFormInstanceId = New Guid("ed807a08-e800-41c2-9e05-a6da01eb4493")
		MyBase.RecordType = "Interaction"
		MyBase.ContextRecordType = "CONSTITUENT"
		MyBase.FORMHEADER.Value = "Add OCM Customizations to Web Sponsorships"
		MyBase.UserInterfaceUrl = "browser/htmlforms/AddCustomizationsToWebSponsorships.html"

		'
		'_sponsorshipconstituentid
		'
		_sponsorshipconstituentid.Name = "SPONSORSHIPCONSTITUENTID"
		_sponsorshipconstituentid.Caption = "Sponsor ID"
		_sponsorshipconstituentid.Visible = False
		_sponsorshipconstituentid.DBReadOnly = True
		Me.Fields.Add(_sponsorshipconstituentid)
		'
		'_isprospect
		'
		_isprospect.Name = "ISPROSPECT"
		_isprospect.Caption = "Is Prospect"
		_isprospect.Required = True
		Me.Fields.Add(_isprospect)
		'
		'_sponsorname
		'
		_sponsorname.Name = "SPONSORNAME"
		_sponsorname.Caption = "Sponsor"
		_sponsorname.DBReadOnly = True
		_sponsorname.MaxLength = 100
		Me.Fields.Add(_sponsorname)
		'
		'_interactiontypecodeid
		'
		_interactiontypecodeid.Name = "INTERACTIONTYPECODEID"
		_interactiontypecodeid.Caption = "Interaction"
		_interactiontypecodeid.Required = True
		_interactiontypecodeid.CodeTableName = "USR_NEWSPONSORSHIPINTERACTIONTYPECODE"
		Me.Fields.Add(_interactiontypecodeid)
		'
		'_pfmid
		'
		_pfmid.Name = "PFMID"
		_pfmid.Caption = "Partner"
		_pfmid.SearchListID = New Guid("a00235ec-b143-4f50-ad74-4c653d605cdf")
		_pfmid.EnableQuickFind = True
		Me.Fields.Add(_pfmid)
		'
		'_filterdate
		'
		_filterdate.Name = "FILTERDATE"
		_filterdate.Caption = "Sponsorship Date"
		Me.Fields.Add(_filterdate)
		'
		'_children
		'
		_children.Name = "CHILDREN"
		_children.Caption = "Children"
		Me.Fields.Add(_children)
		'
		'_sponsorshipopportunityidchild
		'
		_sponsorshipopportunityidchild.Name = "SPONSORSHIPOPPORTUNITYIDCHILD"
		_sponsorshipopportunityidchild.Caption = "Child Lookup ID"
		Me.Fields.Add(_sponsorshipopportunityidchild)
		'
		'_findchildren
		'
		_findchildren.Name = "FINDCHILDREN"
		_findchildren.Caption = "Find Children"
		Me.Actions.Add(_findchildren)
		'
		'_addselectedchild
		'
		_addselectedchild.Name = "ADDSELECTEDCHILD"
		_addselectedchild.Caption = "Add Child"
		Me.Actions.Add(_addselectedchild)
		'
		'_removeselectedchild
		'
		_removeselectedchild.Name = "REMOVESELECTEDCHILD"
		_removeselectedchild.Caption = "Remove Child"
		Me.Actions.Add(_removeselectedchild)

		OnCreated()

	End Sub

	''' <summary>
	''' Sponsor ID
	''' </summary>
	<System.ComponentModel.Description("Sponsor ID")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SPONSORSHIPCONSTITUENTID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		Get
			Return _sponsorshipconstituentid
		End Get
	End Property

	''' <summary>
	''' Is Prospect
	''' </summary>
	<System.ComponentModel.Description("Is Prospect")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [ISPROSPECT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		Get
			Return _isprospect
		End Get
	End Property

	''' <summary>
	''' Sponsor
	''' </summary>
	<System.ComponentModel.Description("Sponsor")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SPONSORNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _sponsorname
		End Get
	End Property

	''' <summary>
	''' Interaction
	''' </summary>
	<System.ComponentModel.Description("Interaction")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [INTERACTIONTYPECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
		Get
			Return _interactiontypecodeid
		End Get
	End Property

	''' <summary>
	''' Partner
	''' </summary>
	<System.ComponentModel.Description("Partner")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [PFMID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
		Get
			Return _pfmid
		End Get
	End Property

	''' <summary>
	''' Sponsorship Date
	''' </summary>
	<System.ComponentModel.Description("Sponsorship Date")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [FILTERDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
		Get
			Return _filterdate
		End Get
	End Property

	''' <summary>
	''' Children
	''' </summary>
	<System.ComponentModel.Description("Children")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [CHILDREN]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of AddWebSponsorshipOnBoardingInteractionsCHILDRENUIModel)
		Get
			Return _children
		End Get
	End Property

	''' <summary>
	''' Child Lookup ID
	''' </summary>
	<System.ComponentModel.Description("Child Lookup ID")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SPONSORSHIPOPPORTUNITYIDCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _sponsorshipopportunityidchild
		End Get
	End Property
    
    ''' <summary>
    ''' Find Children
    ''' </summary>
    <System.ComponentModel.Description("Find Children")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FINDCHILDREN]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _findchildren
        End Get
    End Property
    
    ''' <summary>
    ''' Add Child
    ''' </summary>
    <System.ComponentModel.Description("Add Child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ADDSELECTEDCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _addselectedchild
        End Get
    End Property
    
    ''' <summary>
    ''' Remove Child
    ''' </summary>
    <System.ComponentModel.Description("Remove Child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REMOVESELECTEDCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _removeselectedchild
        End Get
    End Property
    
End Class
